### ISSUE TITLE
onInterceptTouchEvent always returns false

### ISSUE THREAD

**Issue by CodeZilla7** [nicholasrout/rugby-ranker#11] opened 2018-10-28 18:24 UTC
The Nick I found an issue in the **onInterceptTouchEvent** function of [OnBackgroundClickItemTouchListener.kt](rugby-ranker/common/src/main/java/com/ricknout/rugbyranker/common/ui/OnBackgroundClickItemTouchListener.kt), it always returns false and doesn't return the value returned by **         gestureDetector.onTouchEvent(e)**

**Comment by nicholasrout** [comment] 2018-10-28 18:45
Hey @CodeZilla7, that is intentional. Returning `true` from this function would cause `OnBackgroundClickItemTouchListener` to start intercepting touch events. We only want to know that a touch has occurred, not intercept it. The purpose of this class is to allow for the peeked part of the bottom sheet (i.e. the bit that holds the horizontal list of match prediction chips) to be tapped to cause the bottom sheet to expand, but we don't want to prevent that `RecyclerView` from being scrolled. Thanks for the concern, but I am going to close this because it's working as intended.

**Closed by nicholasrout** 2018-10-28 18:45 UTC
